version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: iot_postgres_db
    restart: always
    environment:
      POSTGRES_USER: kmp_iot_user
      POSTGRES_PASSWORD: kmp_iot_password
      POSTGRES_DB: kmp_iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      
  ktor-server:
    build: .
    container_name: iot_ktor_server
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - db
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mqtt_broker
      - DATABASE_URL=jdbc:postgresql://iot_postgres_db:5432/kmp_iot_db

volumes:
  postgres_data:
