package caonguyen.vu.shared.buildconfig

// Wrapper object to expose the internal BuildKonfig generated by the plugin
// This fixes WasmJS compilation crashes while allowing Android/iOS to access it.
object BuildKonfig {
    val MQTT_BROKER_HOST: String get() = BuildKonfigInternal.MQTT_BROKER_HOST
    val WEBSOCKET_HOST: String get() = BuildKonfigInternal.WEBSOCKET_HOST
    val MQTT_CMD_TOPIC: String get() = BuildKonfigInternal.MQTT_CMD_TOPIC
    val MQTT_STATUS_TOPIC_FILTER: String get() = BuildKonfigInternal.MQTT_STATUS_TOPIC_FILTER
}
